spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:6033/spring_starter?useUnicode=yes&characterEncoding=UTF-8
    username: admin
    password: admin
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
natsukashiiz:
  jwt:
    issuer: natsukashiiz
    access:
      secret: rBhbLzWnPFPbVUdAnYaHBPWHXNjA5cfJpjuhYPBArxSpLAh2Xm5Jbcr3XMR2W3Pn
      expirationMs: 3600000
    refresh:
      secret: rBhbLzWnPFPbVUdAnYaHBPWHXNjA5cfJpjuhYPBArxSpLAh2Xm5Jbcr3XMR2W3Pn
      expirationMs: 86400000
  rsa:
    private-key: classpath:certs/private.pem
    public-key: classpath:certs/public.pem
logging:
  level:
    org.springframework.web: DEBUG